## Citation Class Overlap Analysis

This notebook evaluates how often patent topic–candidate pairs share at least one IPC class.


### Conclusion
Citation/retrieval pairs are mostly class-consistent (high IPC overlap), but a non-trivial minority lacks class overlap, indicating potentially broader or cross-class citation behavior. Therefore, filtering against IPC prior to the retrieval might lead to dropping some of the relevant citations

In [5]:
import pandas as pd
import plotly.express as px
from pathlib import Path
import os
from patent_retrieval import utils as utils

In [ ]:
# paths to the analysis file output by `patent_class.py` and the test topics file
analysis_path = "/home/alm3rng/patent-retrieval/src/patent_retrieval/dataset/patent_classification_analysis_B00X 000.csv"
test_topics_path=Path(os.environ["CLEF_IP_LOCATION"])/ "02_topics"/ "test-pac"/ "relass_clef-ip-2011-PAC_abs.txt"

In [4]:
classes_df = pd.read_csv(analysis_path)
classes_df

,topic,number,score,topic_ipcrs,doc_ipcrs,common_ipcrs,n_common_ipcrs,tp
0,EP-1221372-A2,WO-2002004219,0.820527,"{'B41J 2/145', 'B41J 2/155', 'B41J 2/05'}","{'B41J 2/145', 'B41J 2/155', 'B41J 2/05'}","{'B41J 2/145', 'B41J 2/155', 'B41J 2/05'}",3,False
1,EP-1221372-A2,EP-1029674,0.798651,"{'B41J 2/145', 'B41J 2/155', 'B41J 2/05'}","{'B41J 2/05', 'B41J 2/01'}",{'B41J 2/05'},1,True
2,EP-1221372-A2,EP-0703079,0.793282,"{'B41J 2/145', 'B41J 2/155', 'B41J 2/05'}",{'B41J 2/05'},{'B41J 2/05'},1,False
3,EP-1221372-A2,EP-1514688,0.789982,"{'B41J 2/145', 'B41J 2/155', 'B41J 2/05'}",{'B41J 2/05'},{'B41J 2/05'},1,False
4,EP-1221372-A2,EP-1193065,0.787915,"{'B41J 2/145', 'B41J 2/155', 'B41J 2/05'}",{'B41J 2/05'},{'B41J 2/05'},1,False
...,...,...,...,...,...,...,...,...
1985495,EP-1936750-A1,WO-2000014584,0.673689,"{'H01R 12/24', 'H01R 12/00', 'H01R 13/52'}",{'G02B 6/38'},set(),0,False
1985496,EP-1936750-A1,EP-1016814,0.673618,"{'H01R 12/24', 'H01R 12/00', 'H01R 13/52'}","{'F16L 3/223', 'F16L 3/04', 'F16L 3/02', 'F16L...",set(),0,False
1985497,EP-1936750-A1,EP-1128473,0.673276,"{'H01R 12/24', 'H01R 12/00', 'H01R 13/52'}","{'H01R 13/22', 'H01R 12/00', 'H01R 13/24', 'H0...",{'H01R 12/00'},1,False
1985498,EP-1936750-A1,EP-0681136,0.673243,"{'H01R 12/24', 'H01R 12/00', 'H01R 13/52'}","{'F16L 41/08', 'B60R 11/02'}",set(),0,False
1985499,EP-1936750-A1,WO-1997048931,0.673198,"{'H01R 12/24', 'H01R 12/00', 'H01R 13/52'}","{'F16L 5/02', 'H02G 3/22', 'G02B 6/44', 'F16L ...",set(),0,False

In [8]:
classes_df["topic_ipcrs"] = classes_df["topic_ipcrs"].map(lambda x: {c.split()[0] for c in eval(x)})
classes_df["doc_ipcrs"] = classes_df["doc_ipcrs"].map(lambda x: {c.split()[0] for c in eval(x)})

In [9]:
classes_df['common_ipcrs'] = classes_df.apply(
    lambda r: (r['topic_ipcrs'] or set()).intersection(r['doc_ipcrs'] or set()),
    axis=1
)

classes_df['n_common_ipcrs'] = classes_df['common_ipcrs'].apply(len)

In [10]:
classes_df

,topic,number,score,topic_ipcrs,doc_ipcrs,common_ipcrs,n_common_ipcrs,tp
0,EP-1221372-A2,WO-2002004219,0.820527,{B41J},{B41J},{B41J},1,False
1,EP-1221372-A2,EP-1029674,0.798651,{B41J},{B41J},{B41J},1,True
2,EP-1221372-A2,EP-0703079,0.793282,{B41J},{B41J},{B41J},1,False
3,EP-1221372-A2,EP-1514688,0.789982,{B41J},{B41J},{B41J},1,False
4,EP-1221372-A2,EP-1193065,0.787915,{B41J},{B41J},{B41J},1,False
...,...,...,...,...,...,...,...,...
1985495,EP-1936750-A1,WO-2000014584,0.673689,{H01R},{G02B},{},0,False
1985496,EP-1936750-A1,EP-1016814,0.673618,{H01R},"{F16L, F16B, D03D}",{},0,False
1985497,EP-1936750-A1,EP-1128473,0.673276,{H01R},{H01R},{H01R},1,False
1985498,EP-1936750-A1,EP-0681136,0.673243,{H01R},"{F16L, B60R}",{},0,False
1985499,EP-1936750-A1,WO-1997048931,0.673198,{H01R},"{F16L, G02B, H02G}",{},0,False

In [45]:
classes_df_top200 = classes_df.groupby('topic').head(100).reset_index(drop=True)
classes_df_top200

,topic,number,score,topic_ipcrs,doc_ipcrs,common_ipcrs,n_common_ipcrs,tp
0,EP-1221372-A2,WO-2002004219,0.820527,{B41J},{B41J},{B41J},1,False
1,EP-1221372-A2,EP-1029674,0.798651,{B41J},{B41J},{B41J},1,True
2,EP-1221372-A2,EP-0703079,0.793282,{B41J},{B41J},{B41J},1,False
3,EP-1221372-A2,EP-1514688,0.789982,{B41J},{B41J},{B41J},1,False
4,EP-1221372-A2,EP-1193065,0.787915,{B41J},{B41J},{B41J},1,False
...,...,...,...,...,...,...,...,...
397095,EP-1936750-A1,EP-0504736,0.714389,{H01R},"{F16L, H05K, H02G, B60R}",{},0,False
397096,EP-1936750-A1,WO-2001082435,0.714373,{H01R},"{H01B, H02G}",{},0,False
397097,EP-1936750-A1,EP-1089391,0.713711,{H01R},{H01R},{H01R},1,False
397098,EP-1936750-A1,EP-1058349,0.713615,{H01R},{H01R},{H01R},1,False
397099,EP-1936750-A1,EP-0844718,0.713219,{H01R},{H02G},{},0,False

In [47]:
share_counts = (
    (classes_df_top200["n_common_ipcrs"] > 0)
    .map({True: "share >=1 class", False: "share 0 classes"})
    .value_counts()
    .rename_axis("pair_type")
    .reset_index(name="count")
)

share_counts["pct"] = 100 * share_counts["count"] / share_counts["count"].sum()
share_counts["label"] = share_counts["pct"].map(lambda x: f"{x:.1f}%")

fig = px.bar(
    share_counts,
    x="pair_type",
    y="count",
    text="label",
    title="Topic–candidate pairs: at least one shared class vs none"
)
fig.update_traces(textposition="outside")
fig.update_layout(xaxis_title="", yaxis_title="Number of pairs")
fig.show()

In [16]:
topics_df = utils.load_topics_df(test_topics_path)
topics_df

               topic   candidate  score
0      EP-1221372-A2  EP-0229673      1
1      EP-1221372-A2  EP-0271257      1
2      EP-1221372-A2  EP-0445916      1
3      EP-1221372-A2  EP-0512799      1
4      EP-1221372-A2  EP-0547921      1
...              ...         ...    ...
19557  EP-1936237-A1  EP-0252423      2
19558  EP-1936237-A1  EP-0320621      1
19559  EP-1936750-A1  EP-0948090      2
19560  EP-1936750-A1  EP-0948092      2
19561  EP-1936750-A1  EP-1030425      2

[19562 rows x 3 columns]

In [34]:
topic_to_ipcrs = classes_df.groupby("topic")["topic_ipcrs"].first()
topics_df["topic_ipcrs"] = topics_df["topic"].map(topic_to_ipcrs)
candidates_to_ipcrs = classes_df.groupby("number")["doc_ipcrs"].first()
topics_df["candidate_ipcrs"] = topics_df["candidate"].map(candidates_to_ipcrs)

topics_df

               topic   candidate  score topic_ipcrs candidate_ipcrs
0      EP-1221372-A2  EP-0229673      1      {B41J}             NaN
1      EP-1221372-A2  EP-0271257      1      {B41J}             NaN
2      EP-1221372-A2  EP-0445916      1      {B41J}          {B41J}
3      EP-1221372-A2  EP-0512799      1      {B41J}             NaN
4      EP-1221372-A2  EP-0547921      1      {B41J}          {B41J}
...              ...         ...    ...         ...             ...
19557  EP-1936237-A1  EP-0252423      2      {F16H}    {F16H, F15B}
19558  EP-1936237-A1  EP-0320621      1      {F16H}          {F16H}
19559  EP-1936750-A1  EP-0948090      2      {H01R}          {H01R}
19560  EP-1936750-A1  EP-0948092      2      {H01R}          {H01R}
19561  EP-1936750-A1  EP-1030425      2      {H01R}    {H01R, H02G}

[19562 rows x 5 columns]

In [ ]:
topics_df['common_ipcrs'] = topics_df.apply(
    lambda r: (
        r['topic_ipcrs'] if isinstance(r['topic_ipcrs'], set) else set()
    ).intersection(
        r['candidate_ipcrs'] if isinstance(r['candidate_ipcrs'], set) else set()
    ),
    axis=1
)
topics_df['n_common_ipcrs'] = topics_df['common_ipcrs'].apply(len)

In [ ]:
share_counts = (
    (topics_df["n_common_ipcrs"] > 0)
    .map({True: "share >=1 class", False: "share 0 classes"})
    .value_counts()
    .rename_axis("pair_type")
    .reset_index(name="count")
)

share_counts["pct"] = 100 * share_counts["count"] / share_counts["count"].sum()
share_counts["label"] = share_counts["pct"].map(lambda x: f"{x:.1f}%")

fig = px.bar(
    share_counts,
    x="pair_type",
    y="count",
    text="label",
    title="Topic–candidate pairs: at least one shared class vs none"
)
fig.update_traces(textposition="outside")
fig.update_layout(xaxis_title="", yaxis_title="Number of pairs")
fig.show()

## Summary of Insights

**Analysis 1 – Citation pairs (top-100 candidates per topic):**
- **79.8%** of topic–candidate pairs share at least one IPC class.
- **20.2%** share zero IPC classes.

**Analysis 2 – Full test-set topic–candidate pairs:**
- **85.0%** share at least one IPC class.
- **15.0%** share zero IPC classes.

**Key takeaways:**
1. The majority of citation/retrieval pairs are **class-consistent**, confirming that IPC classification is a strong signal for patent relevance.
2. However, a **non-trivial minority (15–20%)** of relevant citations fall outside the topic's IPC classes, indicating cross-class citation behavior.
3. Using IPC as a hard pre-filter for retrieval would **discard 15–20% of true relevant documents**, making it a risky strategy unless recall loss is acceptable.
4. IPC could still be useful as a **soft signal** (e.g., boosting scores for same-class candidates) rather than a strict filter.